server:
  port: 8080

spring:
  application:
    name: _8080-jilijili-Gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:9111"
            allowCredentials: true
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 2000
        response-timeout: 60s
      routes:
        - id: _11111-jilijili-blog
          uri: http://127.0.0.1:11111
          predicates:
            - Path=/blog/**
        - id: _11112_jilijili_video
          uri: http://127.0.0.1:11112
          predicates:
            - Path=/video/**
        - id: _11114_jilijili_shop
          uri: http://127.0.0.1:11114
          predicates:
            - Path=/shop/**