spring:
  application:
    name: 8080-jilijili-Gateway
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      globalcors: # 全局的跨域配置
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: # 允许哪些网站的跨域请求
              - "*"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"    # 允许在请求中携带的头信息
            allowCredentials: true    # 允许在请求中携带cookie
            maxAge: 360000            # 本次跨域检测的有效期(单位毫秒)
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: 1110-jilijili-system
#          #          uri: lb://1110-jilijili-system
#          uri: http://localhost:11110
#          predicates:
#            - Path=/system/**
#        - id: _1111-jilijili-blog
#          #          uri: lb://_1111-jilijili-blog
#          uri: http://localhost:11111
#          predicates:
#            - Path=/blog**

