# 配置端口
server:
  port: ${APPLICATION_PORT}
  servlet:
    session:
      timeout: 21600

spring:
  # 配置mysql数据库
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:mysql://${MYSQL_H0ST}:${MYSQL_PORT}/${DATABASE_NAME_1}?serverTimezone=Asia/Shanghai&allowMultiQueries=true
          username: ${MYSQL_USER_NAME:root}
          password: ${MYSQL_PASSWORD:123456}
          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
          hikari:
            connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
            minIdle: 5 # 最小连接数
            maxPoolSize: 10 # 最大连接数
            isAutoCommit: true # 自动提交
            idleTimeout: 600000 # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
            maxLifetime: 1800000 # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
            connection-test-query: SELECT 1 FROM DUAL
            data-source-properties: #以下属性仅为演示（默认不会引入）
        slave_1:
          url: jdbc:mysql://${MYSQL_H0ST}:${MYSQL_PORT}/${DATABASE_NAME_2}?serverTimezone=Asia/Shanghai&allowMultiQueries=true
          username: ${MYSQL_USER_NAME:root}
          password: ${MYSQL_PASSWORD:123456}
          driver-class-name: com.mysql.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${MYSQL_H0ST}:${MYSQL_PORT}/${DATABASE_NAME_1}?serverTimezone=Asia/Shanghai&allowMultiQueries=true
#    username: ${MYSQL_USER_NAME:root}
#    password: ${MYSQL_PASSWORD:123456}
#    hikari:
#      #最小空闲连接数量
#      minimum-idle: 5
#      #从池返回的连接默认自动提交
#      auto-commit: true
#      #空闲连接最大时间，10秒
#      idle-timeout: 10000
#      #连接池名字
#      pool-name: StoreHikariCP
#      #池中连接的最长生命周期
#      max-lifetime: 1800000
#      #数据库连接的超时时间
#      connection-timeout: 30000
#      connection-test-query: SELECT 1

  # mq配置
  rabbitmq:
    host: 110.40.230.65
    port: 5672
    username: admin_A
    password: admin_A
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3 #最大重试次数
          initial-interval: 3000 #重试间隔时间（单位毫秒）

  # es配置 若搜索模式为mysql可删除
  elasticsearch:
    rest:
      uris: 110.40.230.65:9200

  # 邮箱配置
  mail:
    host: smtp.qq.com
    username: 1918652173@qq.com
    password: apnxignovcgdcagf
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
      smtp:
      auth: true
      socketFactory:
      class: javax.net.ssl.SSLSocketFactory

  # 上传图片大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  data:
    redis:
      host: 110.40.230.65
      port: 6370
      password: 123456

    # sql版本控制
  flyway:
    enabled: false
    encoding: UTF-8
    locations: classpath:db/migration
    baseline-on-migrate: true
  sql:
    init:
      continue-on-error: false
      platform: h2

  security:
    user:
      password: 123456
      name: admin

# 配置MybatisPlus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

wx:
  appId: ${WX_APPID}
  appSecret: ${WX_APPSECRET}


