# 配置端口
server:
  port: 80
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
spring:
  application:
    name: jilijili-system
  banner:
    location: banner/banner.txt
  config:
    import: optional:file:.env[.properties]
  profiles:
    #    active: dev
    active: pro

