# 配置端口
server:
  port: 80
spring:
  application:
    name: jilijili-music
  banner:
    location: banner/banner.txt
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
#    active: pro

